// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package database

import (
	"context"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO company (
    name, gst, address
) VALUES (
    ?, ?, ?
)
RETURNING id, name, gst, address
`

type CreateCompanyParams struct {
	Name    string
	Gst     string
	Address string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.Gst, arg.Address)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gst,
		&i.Address,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM company
WHERE id = ?
`

func (q *Queries) DeleteCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, gst, address FROM company
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gst,
		&i.Address,
	)
	return i, err
}

const listCompany = `-- name: ListCompany :many
SELECT id, name, gst, address FROM company
`

func (q *Queries) ListCompany(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gst,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE company
SET name = ?,
gst = ?,
address = ?
WHERE id = ?
RETURNING id, name, gst, address
`

type UpdateCompanyParams struct {
	Name    string
	Gst     string
	Address string
	ID      int64
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.Name,
		arg.Gst,
		arg.Address,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gst,
		&i.Address,
	)
	return i, err
}
