// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice_item.sql

package database

import (
	"context"
)

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_item (
    fk_invoice, fk_item, qty
) VALUES (
    ?, ?, ?
)
RETURNING id, fk_invoice, fk_item, qty, created_at, updated_at
`

type CreateInvoiceItemParams struct {
	FkInvoice int64
	FkItem    int64
	Qty       int64
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, createInvoiceItem, arg.FkInvoice, arg.FkItem, arg.Qty)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.FkInvoice,
		&i.FkItem,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoiceItem = `-- name: DeleteInvoiceItem :exec
DELETE FROM invoice_item
WHERE id = ?
`

func (q *Queries) DeleteInvoiceItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvoiceItem, id)
	return err
}

const getInvoiceItem = `-- name: GetInvoiceItem :one
SELECT id, fk_invoice, fk_item, qty, created_at, updated_at FROM invoice_item
WHERE id = ? LIMIT 1
`

func (q *Queries) GetInvoiceItem(ctx context.Context, id int64) (InvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceItem, id)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.FkInvoice,
		&i.FkItem,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoiceItem = `-- name: ListInvoiceItem :many
SELECT id, fk_invoice, fk_item, qty, created_at, updated_at FROM invoice_item
`

func (q *Queries) ListInvoiceItem(ctx context.Context) ([]InvoiceItem, error) {
	rows, err := q.db.QueryContext(ctx, listInvoiceItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.FkInvoice,
			&i.FkItem,
			&i.Qty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceItem = `-- name: UpdateInvoiceItem :one
UPDATE invoice_item
SET fk_invoice = ?,
fk_item = ?,
qty = ?
WHERE id = ?
RETURNING id, fk_invoice, fk_item, qty, created_at, updated_at
`

type UpdateInvoiceItemParams struct {
	FkInvoice int64
	FkItem    int64
	Qty       int64
	ID        int64
}

func (q *Queries) UpdateInvoiceItem(ctx context.Context, arg UpdateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceItem,
		arg.FkInvoice,
		arg.FkItem,
		arg.Qty,
		arg.ID,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.FkInvoice,
		&i.FkItem,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
