// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package database

import (
	"context"
	"time"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoice (
    invoice_number,
    date,
    fk_from_company,
    fk_to_company,
    fk_payment_detail,
    igst,
    total,
    fk_shipping_address
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, invoice_number, date, created_at, updated_at, fk_from_company, fk_to_company, fk_payment_detail, igst, total, fk_shipping_address
`

type CreateInvoiceParams struct {
	InvoiceNumber     int64
	Date              time.Time
	FkFromCompany     int64
	FkToCompany       int64
	FkPaymentDetail   int64
	Igst              float64
	Total             float64
	FkShippingAddress int64
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.Date,
		arg.FkFromCompany,
		arg.FkToCompany,
		arg.FkPaymentDetail,
		arg.Igst,
		arg.Total,
		arg.FkShippingAddress,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FkFromCompany,
		&i.FkToCompany,
		&i.FkPaymentDetail,
		&i.Igst,
		&i.Total,
		&i.FkShippingAddress,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE from invoice
WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, invoice_number, date, created_at, updated_at, fk_from_company, fk_to_company, fk_payment_detail, igst, total, fk_shipping_address FROM invoice
WHERE id = ? LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FkFromCompany,
		&i.FkToCompany,
		&i.FkPaymentDetail,
		&i.Igst,
		&i.Total,
		&i.FkShippingAddress,
	)
	return i, err
}

const getLatestInvoiceNumber = `-- name: GetLatestInvoiceNumber :one
SELECT invoice_number FROM invoice
ORDER BY invoice_number DESC
LIMIT 1
`

func (q *Queries) GetLatestInvoiceNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestInvoiceNumber)
	var invoice_number int64
	err := row.Scan(&invoice_number)
	return invoice_number, err
}

const listInvoice = `-- name: ListInvoice :many
SELECT id, invoice_number, date, created_at, updated_at, fk_from_company, fk_to_company, fk_payment_detail, igst, total, fk_shipping_address FROM invoice
`

func (q *Queries) ListInvoice(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FkFromCompany,
			&i.FkToCompany,
			&i.FkPaymentDetail,
			&i.Igst,
			&i.Total,
			&i.FkShippingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoice
SET invoice_number = ?,
date = ?,
updated_at = ?,
fk_from_company = ?,
fk_to_company = ?,
fk_payment_detail = ?,
igst = ?,
total = ?,
fk_shipping_address = ?
WHERE id = ?
RETURNING id, invoice_number, date, created_at, updated_at, fk_from_company, fk_to_company, fk_payment_detail, igst, total, fk_shipping_address
`

type UpdateInvoiceParams struct {
	InvoiceNumber     int64
	Date              time.Time
	UpdatedAt         time.Time
	FkFromCompany     int64
	FkToCompany       int64
	FkPaymentDetail   int64
	Igst              float64
	Total             float64
	FkShippingAddress int64
	ID                int64
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.InvoiceNumber,
		arg.Date,
		arg.UpdatedAt,
		arg.FkFromCompany,
		arg.FkToCompany,
		arg.FkPaymentDetail,
		arg.Igst,
		arg.Total,
		arg.FkShippingAddress,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FkFromCompany,
		&i.FkToCompany,
		&i.FkPaymentDetail,
		&i.Igst,
		&i.Total,
		&i.FkShippingAddress,
	)
	return i, err
}
