// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package database

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO item (
    name, hsn, price, gst
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, hsn, price, gst, created_at, updated_at
`

type CreateItemParams struct {
	Name  string
	Hsn   int64
	Price float64
	Gst   int64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Name,
		arg.Hsn,
		arg.Price,
		arg.Gst,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hsn,
		&i.Price,
		&i.Gst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM item
where id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, name, hsn, price, gst, created_at, updated_at FROM item
WHERE id = ? LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hsn,
		&i.Price,
		&i.Gst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItem = `-- name: ListItem :many
SELECT id, name, hsn, price, gst, created_at, updated_at FROM item
`

func (q *Queries) ListItem(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hsn,
			&i.Price,
			&i.Gst,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE item
SET name = ?,
hsn = ?,
price = ?,
gst = ?
WHERE id = ?
RETURNING id, name, hsn, price, gst, created_at, updated_at
`

type UpdateItemParams struct {
	Name  string
	Hsn   int64
	Price float64
	Gst   int64
	ID    int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.Name,
		arg.Hsn,
		arg.Price,
		arg.Gst,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hsn,
		&i.Price,
		&i.Gst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
