// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Company struct {
	ID                 int64
	Name               string
	Gst                string
	Address            string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SignatureImagePath string
}

type Invoice struct {
	ID                int64
	InvoiceNumber     int64
	Date              time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	FkFromCompany     int64
	FkToCompany       int64
	FkPaymentDetail   int64
	Igst              float64
	Total             float64
	FkShippingAddress int64
}

type InvoiceItem struct {
	ID        int64
	FkInvoice int64
	FkItem    int64
	Qty       int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Item struct {
	ID        int64
	Name      string
	Hsn       int64
	Price     float64
	Gst       int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PaymentDetail struct {
	ID                 int64
	AccHolder          string
	AccNumber          int64
	Ifsc               string
	Branch             string
	BankName           string
	VirtualPaymentAddr string
	FkCompanyID        int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ShippingAddress struct {
	ID        int64
	Name      string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
