// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_detail.sql

package database

import (
	"context"
)

const createPaymentDetail = `-- name: CreatePaymentDetail :one
INSERT INTO payment_detail (
    acc_holder, acc_number, ifsc, branch, bank_name,
    virtual_payment_addr, fk_company_id
) VALUES (
    ?, ?, ?, ?, ?, 
    ?, ?
)
RETURNING id, acc_holder, acc_number, ifsc, branch, bank_name, virtual_payment_addr, fk_company_id, created_at, updated_at
`

type CreatePaymentDetailParams struct {
	AccHolder          string
	AccNumber          int64
	Ifsc               string
	Branch             string
	BankName           string
	VirtualPaymentAddr string
	FkCompanyID        int64
}

func (q *Queries) CreatePaymentDetail(ctx context.Context, arg CreatePaymentDetailParams) (PaymentDetail, error) {
	row := q.db.QueryRowContext(ctx, createPaymentDetail,
		arg.AccHolder,
		arg.AccNumber,
		arg.Ifsc,
		arg.Branch,
		arg.BankName,
		arg.VirtualPaymentAddr,
		arg.FkCompanyID,
	)
	var i PaymentDetail
	err := row.Scan(
		&i.ID,
		&i.AccHolder,
		&i.AccNumber,
		&i.Ifsc,
		&i.Branch,
		&i.BankName,
		&i.VirtualPaymentAddr,
		&i.FkCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePaymentDetail = `-- name: DeletePaymentDetail :exec
DELETE FROM payment_detail
WHERE id = ?
`

func (q *Queries) DeletePaymentDetail(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePaymentDetail, id)
	return err
}

const getPaymentDetailWithCompanyID = `-- name: GetPaymentDetailWithCompanyID :one
SELECT id, acc_holder, acc_number, ifsc, branch, bank_name, virtual_payment_addr, fk_company_id, created_at, updated_at FROM payment_detail
WHERE fk_company_id = ? LIMIT 1
`

func (q *Queries) GetPaymentDetailWithCompanyID(ctx context.Context, fkCompanyID int64) (PaymentDetail, error) {
	row := q.db.QueryRowContext(ctx, getPaymentDetailWithCompanyID, fkCompanyID)
	var i PaymentDetail
	err := row.Scan(
		&i.ID,
		&i.AccHolder,
		&i.AccNumber,
		&i.Ifsc,
		&i.Branch,
		&i.BankName,
		&i.VirtualPaymentAddr,
		&i.FkCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentDetailWithID = `-- name: GetPaymentDetailWithID :one
SELECT id, acc_holder, acc_number, ifsc, branch, bank_name, virtual_payment_addr, fk_company_id, created_at, updated_at FROM payment_detail
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaymentDetailWithID(ctx context.Context, id int64) (PaymentDetail, error) {
	row := q.db.QueryRowContext(ctx, getPaymentDetailWithID, id)
	var i PaymentDetail
	err := row.Scan(
		&i.ID,
		&i.AccHolder,
		&i.AccNumber,
		&i.Ifsc,
		&i.Branch,
		&i.BankName,
		&i.VirtualPaymentAddr,
		&i.FkCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentDetail = `-- name: ListPaymentDetail :many
SELECT id, acc_holder, acc_number, ifsc, branch, bank_name, virtual_payment_addr, fk_company_id, created_at, updated_at FROM payment_detail
`

func (q *Queries) ListPaymentDetail(ctx context.Context) ([]PaymentDetail, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentDetail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentDetail
	for rows.Next() {
		var i PaymentDetail
		if err := rows.Scan(
			&i.ID,
			&i.AccHolder,
			&i.AccNumber,
			&i.Ifsc,
			&i.Branch,
			&i.BankName,
			&i.VirtualPaymentAddr,
			&i.FkCompanyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentDetail = `-- name: UpdatePaymentDetail :one
UPDATE payment_detail
SET acc_holder = ?,
acc_number = ?,
ifsc = ?,
branch = ?,
bank_name = ?,
virtual_payment_addr = ?,
fk_company_id = ?
WHERE id = ?
RETURNING id, acc_holder, acc_number, ifsc, branch, bank_name, virtual_payment_addr, fk_company_id, created_at, updated_at
`

type UpdatePaymentDetailParams struct {
	AccHolder          string
	AccNumber          int64
	Ifsc               string
	Branch             string
	BankName           string
	VirtualPaymentAddr string
	FkCompanyID        int64
	ID                 int64
}

func (q *Queries) UpdatePaymentDetail(ctx context.Context, arg UpdatePaymentDetailParams) (PaymentDetail, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentDetail,
		arg.AccHolder,
		arg.AccNumber,
		arg.Ifsc,
		arg.Branch,
		arg.BankName,
		arg.VirtualPaymentAddr,
		arg.FkCompanyID,
		arg.ID,
	)
	var i PaymentDetail
	err := row.Scan(
		&i.ID,
		&i.AccHolder,
		&i.AccNumber,
		&i.Ifsc,
		&i.Branch,
		&i.BankName,
		&i.VirtualPaymentAddr,
		&i.FkCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
