// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipping_address.sql

package database

import (
	"context"
)

const createShippingAddress = `-- name: CreateShippingAddress :one
INSERT INTO shipping_address (
    name, address
) VALUES (
    ?, ?
)
RETURNING id, name, address
`

type CreateShippingAddressParams struct {
	Name    string
	Address string
}

func (q *Queries) CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, createShippingAddress, arg.Name, arg.Address)
	var i ShippingAddress
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const deleteShippingAddress = `-- name: DeleteShippingAddress :exec
DELETE FROM shipping_address
WHERE id = ?
`

func (q *Queries) DeleteShippingAddress(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShippingAddress, id)
	return err
}

const getShippingAddress = `-- name: GetShippingAddress :one
SELECT id, name, address FROM shipping_address
WHERE id = ? LIMIT 1
`

func (q *Queries) GetShippingAddress(ctx context.Context, id int64) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, getShippingAddress, id)
	var i ShippingAddress
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const listShippingAddress = `-- name: ListShippingAddress :many
SELECT id, name, address FROM shipping_address
`

func (q *Queries) ListShippingAddress(ctx context.Context) ([]ShippingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listShippingAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingAddress
	for rows.Next() {
		var i ShippingAddress
		if err := rows.Scan(&i.ID, &i.Name, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShippingAddress = `-- name: UpdateShippingAddress :one
UPDATE shipping_address
SET name = ?,
address = ?
WHERE id = ?
RETURNING id, name, address
`

type UpdateShippingAddressParams struct {
	Name    string
	Address string
	ID      int64
}

func (q *Queries) UpdateShippingAddress(ctx context.Context, arg UpdateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, updateShippingAddress, arg.Name, arg.Address, arg.ID)
	var i ShippingAddress
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}
